version: "3.9"
services:
  holamundonodemon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: holamundonodemon
    image: node
    volumes:
      - .:/home/app
    ports:
      - "3000:3000"
    restart: always
    command: ["./run.sh"]